livecycle/preevy

site/docs/intro/getting-started.mdx
I also think we should add a title above "Install the CLI globally" as right now it disappears under the "info" box
=> Minor content edits

packages/cli/src/commands/purge.ts, packages/cli/src/commands/up/index.ts, packages/cli/src/lib/commands/up/machine.ts, packages/cli/src/lib/machine/driver/driver.ts, packages/cli/src/lib/machine/drivers/fake/index.ts, packages/cli/src/lib/machine/drivers/lightsail/bundle-id.ts, packages/cli/src/lib/machine/drivers/lightsail/client.ts, packages/cli/src/lib/machine/drivers/lightsail/index.ts, packages/cli/src/lib/machine/drivers/lightsail/tags.ts, packages/cli/src/lib/prompt.ts, packages/cli/src/lib/state/ssh.ts, packages/cli/src/migrations/preview-to-preevy-tags.ts
* machine only recreated if bundle-id is overridden in the command line
* refactor tags, rename from preview to preevy (add migration script)
* add purge command to delete all cloud resources
=> add bundle-id arg to lightsail driver

.github/workflows/awesome-lint.yaml, .vscode/extensions.json, .vscode/settings.json, README.md, contributing.md
https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
=> add linter for awesome-list

package.json, packages/cli/README.md, packages/cli/package.json, packages/cli/src/commands/urls.ts, packages/cli/src/lib/compose-tunnel-agent-client.ts, packages/common/package.json, packages/compose-tunnel-agent/package.json
Add retry to url command
Bump version
=> Increased fetch timeout for tunnels

tunnel-server/index.ts, tunnel-server/src/preview-env.ts, tunnel-server/src/proxy.ts, tunnel-server/src/ssh-server.ts, tunnel-server/yarn.lock
=> support private connection requests

packages/core/src/telemetry/emitter.ts, packages/core/src/telemetry/process-exit.ts
This fix missing telemetries on SIGINT signal
=> Fix emitter await behavior when there's a pending flush

README.md
Added some benefits of preview environments to our README.md
=> Improve Preevy readme

site/docusaurus.config.js, site/package.json, site/yarn.lock
apiKey and appId are safe to commit.
=> Create a search input with Algolia api

packages/driver-kube-pod/src/driver/client/exec/index.ts, packages/driver-kube-pod/src/driver/client/exec/kubectl.ts, packages/driver-kube-pod/src/driver/client/index.ts, packages/driver-kube-pod/src/driver/driver.ts, packages/driver-kube-pod/src/driver/questions.ts
Add support for context.
Update Init questions/answers.
Solve #120 
Should be merged after #126
=> Update kube-pod driver

contributing.md, pull_request_template.md
- add requirement to be a Preevy user
- add PR template to make sure guidelines are visible
=> change contribution guidelines

site/docs/intro/getting-started.mdx
- Clear the instructions and add info about Azure and K8s
=> docs: update getting-started page

packages/cli/src/commands/up.ts
Fix: #144 
Console messages have been added for the "preevy up" command to enhance the user experience.
=> Messaging for initial CLI cloud interaction added

README.md
Add a user feedback form to README
=> docs: add a feedback form

packages/cli/src/profile-command.ts, packages/core/src/ci-providers/azure-pipelines.ts, packages/core/src/ci-providers/base.ts, packages/core/src/ci-providers/circle.ts, packages/core/src/ci-providers/github-actions.ts, packages/core/src/ci-providers/gitlab.ts, packages/core/src/ci-providers/travis.ts, packages/core/src/commands/up/index.ts, packages/core/src/commands/up/machine.ts, packages/core/src/driver/driver.ts, packages/core/src/env-metadata.ts
- CI provider ID
- env ID
- driver providerID
=> more metadata 2

.github/workflows/test.yaml, packages/compose-tunnel-agent/package.json, packages/compose-tunnel-agent/src/http/docker-proxy/index.test.ts, packages/core/jest.config.js, packages/core/src/index.ts, packages/core/src/strings.test.ts, packages/core/src/strings.ts, packages/driver-kube-pod/jest.config.js, packages/driver-kube-pod/package.json, packages/driver-kube-pod/src/driver/client/index.ts, packages/driver-kube-pod/src/driver/client/labels.test.ts, packages/driver-kube-pod/src/driver/client/labels.ts, packages/driver-kube-pod/src/driver/client/metadata.test.ts, packages/driver-kube-pod/src/driver/client/metadata.ts, packages/driver-kube-pod/tsconfig.json, yarn.lock
=> kube driver: fix sanitation

packages/driver-kube-pod/src/driver/driver.ts, packages/driver-kube-pod/src/driver/questions.ts
=> kube driver: init with default context

.github/workflows/test.yaml, tunnel-server/index.ts, tunnel-server/jest.config.cjs, tunnel-server/package.json, tunnel-server/src/app.ts, tunnel-server/src/auth.ts, tunnel-server/src/http-server-helpers.ts, tunnel-server/src/preview-env.ts, tunnel-server/src/proxy.ts, tunnel-server/src/proxy/index.ts, tunnel-server/src/proxy/router.test.ts, tunnel-server/src/proxy/router.ts, tunnel-server/src/ssh/index.ts, tunnel-server/src/tunnel-store.ts, tunnel-server/yarn.lock
- minor refactor
- minor refactor isProxyRequest
- tunnel server: add proxy access with path
=> proxy access with path

tunnel-server/index.ts, tunnel-server/src/app.ts, tunnel-server/src/auth.ts, tunnel-server/src/proxy/index.ts
=> Suuport querying tunnels from the Tunnel Service

tunnel-server/index.ts, tunnel-server/src/proxy/index.ts
=> Fix auth handling when using websocket

packages/cli/src/commands/profile/key.ts, packages/core/src/credentials/index.ts, packages/core/src/index.ts
command can show any of the following
- public key (in PEM or SSH formats)
- private key
- thumbprint (in short or full URI formats)
=> add profile:key command to show key

.github/workflows/gh-release.yaml, Dockerfile.cli
=> Sign Preevy bin

site/docs/drivers/aws-lightsail.md
Update the Preevy-AWS videos in the docs
=> docs: update the AWS video

packages/cli/src/commands/init.ts, packages/cli/src/commands/profile/config/update.ts, packages/cli/src/commands/profile/config/view.ts, packages/cli/src/commands/profile/create.ts, packages/cli/src/commands/profile/import.ts, packages/cli/src/commands/up.ts, packages/cli/src/driver-command.ts, packages/cli/src/profile-command.ts, packages/core/src/profile/config.ts, packages/core/src/profile/profile.ts, packages/core/src/profile/store.ts
Add --profile for all driver/profile commands
Add --use flag for preevy:create and preevy:import.
Add support for setting --driver in preevy:config:update
=> Preey profile improvements

site/docs/drivers/gcp-gce.md
=> docs: Add gcp preevy video to docs

tunnel-server/src/ssh/index.ts
=> fix race condition

packages/cli/src/commands/proxy/connect.ts, packages/cli/src/commands/up.ts, packages/cli/src/commands/urls.ts, packages/common/src/ssh/base-client.ts, packages/compose-tunnel-agent/index.ts, packages/compose-tunnel-agent/src/ssh/tunnel-client.ts, packages/core/src/tunneling/tunnel-server-client.ts
- cta: well behaved close
- cta: limit shutdown timeout
=> cta well behaved close

tunnel-server/package.json, tunnel-server/src/destroy-server.test.ts, tunnel-server/src/destroy-server.ts, tunnel-server/src/ssh/base-server.ts, tunnel-server/yarn.lock
- tunnel server: more aggressive destroy
=> tunnel server more aggressive destroy

README.md
Update the new Slack Community link.
=> docs: update the new slack community link

tunnel-server/src/proxy/html-manipulation/index.ts, tunnel-server/src/proxy/html-manipulation/inject-transform.ts, tunnel-server/src/proxy/index.ts, tunnel-server/src/tunnel-store/index.ts
when injecting, responses were not compressed.
also fixed wrong chunked response.
=> tunnel server: fix encoding

site/docs/drivers/azure.md
=> docs: update the azure video

site/docs/intro/getting-started.mdx
Add a Note to make sure have a git initialized repo and have at least one commit
=> docs: add a instruction

README.md
Add Livecycle Docker Extesnion Promo
=> docs: add promo for docker extension

README.md
=> docs: fix the text

packages/cli/package.json, packages/cli/src/commands/help.ts, packages/cli/src/help.ts
=> cli: always show global flags on help

site/docs/integrations/docker-extension.md
##Fixed typos and corrected grammar in docker-extension.md
=> Fix typos in docker-extension.md

site/docs/integrations/docker-extension.md
Fix the links in the FAQ section
=> docs: update the livecycle extension docs

README.md, packages/cli/src/driver-command.ts, packages/cli/src/drivers.ts, packages/cli/src/machine-creation-driver-command.ts, packages/core/src/config.ts, packages/driver-azure/src/driver/index.ts, packages/driver-kube-pod/src/driver/client/index.ts, site/docs/drivers/aws-lightsail.md, site/docs/drivers/azure.md, site/docs/drivers/gcp-gce.md, site/docs/drivers/kube-pod.md
- add driver overrides in compose file
- update docs
- remove unused code
=> CLI: add driver override in compose file

packages/cli/src/commands/up.ts, packages/core/src/commands/up/index.ts
=> Added Livecycle widget support (hidden flag)

site/docs/FAQs/docker-extension.md, site/docs/FAQs/livecycle-dashboard.md, site/docs/FAQs/livecycle.md, site/docs/FAQs/preevy.md, site/docs/docker-extension.md, site/docs/intro/getting-started.mdx
- Add FAQ for Extension, Preevy, Saas
=> docs: Add FAQs

packages/driver-kube-pod/src/driver/client/index.ts, packages/driver-kube-pod/src/driver/client/port-forward.ts
attempt to fix hanging process on exit
=> kube driver: release sockets used by kube API

site/docs/docker-extension.md
Add a getting started video tutorial for Livecycle Docker Extension
=> docs: add video tutorial for Livecycle Docker Extension

site/docs/docker-extension.md
Update Livecycle Docker Extension docs
=> docs: Update Docker extension documentation

site/docs/intro/under-the-hood.md, site/docs/tunnel-server.md
- refactor profile description section in "under the hood"
- correct TLS references and add mention of self hosting guide in "tunnel-server"
=> doc site improvements:
