livecycle/preevy

- .vscode/settings.json
- packages/cli/package.json
- packages/cli/src/hooks/init/async-trace.ts
- packages/cli/src/hooks/init/sync-logging.ts
- packages/cli/src/hooks/init/telemetry.ts
- packages/cli/src/hooks/postrun/telemetry.ts
- packages/cli/src/hooks/prerun/telemetry.ts
- packages/compose-tunnel-agent/src/docker.ts
- packages/core/src/sftp-copy.ts
- packages/core/src/telemetry/emitter.ts
fixed #55 
There were 2 problems:
1. We used `debounced` while actually wanted to use `throttle`
2. We relied on Node's `exit` and `beforeExit` process events to cancel throttled flush events, but Node waits for all Promises to end before emitting those events, thus we wait for the `FLUSH_INTERVAL` which is set for eternity (i.e. 5 seconds)
> Fix slow teardown because of telemetry

- site/docs/intro/getting-started.mdx
fix typo from `docker comopse up` -> `docker compose up`
> fix typo in getting-started.mdx

- README.md
> Removed the text "AWS Login" from README

- packages/cli/src/commands/up.ts
- packages/cli/src/commands/urls.ts
- packages/cli/src/tunnel-server-client.ts
- packages/common/src/ssh/base-client.ts
- packages/common/src/ssh/connection-checker.ts
- packages/core/src/commands/up/index.ts
- packages/core/src/commands/urls.ts
- packages/core/src/tunneling/index.ts
- tunnel-server/index.ts
replace `baseUrl` object returned from the `hello` command with `rootUrl` string, in a backwards-compatible way
> baseUrl to rootUrl

- packages/cli/src/commands/profile/config/update.ts
- packages/cli/src/commands/profile/config/view.ts
- packages/cli/src/commands/profile/configure.ts
- packages/cli/src/commands/profile/create.ts
- packages/cli/src/drivers.ts
Fix #23 
Add the command `preevy profile configure`:
Usage examples:
```
preevy profile config view ->
Current configuration for kube-pod:  
namespace:     test123
server-side-apply: false
preevy profile config update --kube-pod-namespace=abc ->
Updated profile configuration
Current configuration for kube-pod:
namespace:     abc
server-side-apply: false
preevy profile config update --unset=kube-pod-server-side-apply ->
preevy profile config update --unset=server-side-apply ->
Updated profile configuration
Current configuration for kube-pod:
namespace:     abc
```
> Add support for configuration of profile

- .github/workflows/npm-publish-canary.yaml
- packages/cli-common/src/lib/hooks.ts
- packages/cli/src/commands/up.ts
- packages/cli/src/commands/urls.ts
- packages/common/src/tunnel-name.ts
- packages/compose-tunnel-agent/src/ssh/tunnel-client.ts
- packages/core/src/commands/up/index.ts
- packages/core/src/commands/urls.ts
- packages/core/src/compose-tunnel-agent-client.ts
- packages/core/src/compose/model.ts
- packages/core/src/credentials/index.ts
- packages/core/src/tunneling/index.ts
- packages/core/src/url.ts
- packages/plugin-github-pr-link/src/hooks.ts
- tunnel-server/src/ssh-server.ts
also contains:
- refactor `projectName` out of `queryTunnels` so the `urls` command would not need a compose file
- fix for bug in tunnel server manifesting when upgrading the compose tunnel agent tunnel access
> make compose tunnel agent tunnel private

- packages/compose-tunnel-agent/index.ts
- packages/compose-tunnel-agent/src/http/api-server.ts
- packages/core/src/ci-providers/azure-pipelines.ts
- packages/core/src/ci-providers/base.ts
- packages/core/src/ci-providers/circle.ts
- packages/core/src/ci-providers/github-actions.ts
- packages/core/src/ci-providers/gitlab.ts
- packages/core/src/ci-providers/travis.ts
- packages/core/src/commands/up/index.ts
- packages/core/src/compose-tunnel-agent-client.ts
- packages/core/src/env-metadata.ts
- packages/core/src/git.ts
> env metadata with git metadata

- packages/core/src/commands/ls.ts
- packages/core/src/driver/driver.ts
- packages/driver-azure/src/driver/index.ts
- packages/driver-gce/src/driver/index.ts
- packages/driver-kube-pod/src/driver/driver.ts
- packages/driver-lightsail/src/driver/index.ts
fixes #159
add `listMachines` in drivers, in addition to `listDeletableResources`
`listMachines` is used by the `ls` command
`listDeletableResources` is used by the `purge` command
For drivers with only machine resources (all but AWS) the two functions are identical. Most of the diff is layout changes due to extracting `listMachines` and using it in two places.
> fix ls showing other resources

- packages/cli/src/commands/up.ts
- packages/common/index.ts
- packages/common/src/json.ts
- packages/compose-tunnel-agent/index.ts
- packages/compose-tunnel-agent/package.json
- packages/compose-tunnel-agent/src/files.ts
- packages/compose-tunnel-agent/src/metadata.ts
- packages/compose-tunnel-agent/tsconfig.json
- packages/core/src/commands/up/index.ts
- packages/core/src/commands/up/machine.ts
- packages/core/src/compose-tunnel-agent-client.ts
- packages/core/src/driver/driver.ts
- packages/core/src/driver/index.ts
- packages/core/src/env-metadata.ts
- packages/core/src/index.ts
- packages/driver-azure/src/driver/index.ts
- packages/driver-gce/src/driver/index.ts
- packages/driver-kube-pod/src/driver/creation-driver.ts
- packages/driver-lightsail/src/driver/index.ts
- allow CTA to load metadata from multiple files in addition to the env var
- add driver metadata
- add creation date and version metadata
> more metadata

- packages/driver-kube-pod/src/driver/client/labels.ts
- packages/driver-kube-pod/src/driver/client/metadata.ts
underscores are not supported according to doc: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
> kube driver: fix sanitation of names

- packages/driver-gce/src/driver/client.ts
- packages/driver-gce/src/driver/index.ts
- packages/driver-gce/src/driver/labels.ts
- packages/driver-gce/src/driver/metadata.ts
label contained the envId as is, which does not adhere to the [allowed characters](https://cloud.google.com/compute/docs/labeling-resources#requirements).
fixed by storing a hash of the envId and profileId, in the labels, which are used as a filter when querying the instances. actual values are stored in the [instance metadata](https://cloud.google.com/compute/docs/metadata/setting-custom-metadata) and returned for the ls command.
fixes #153
> gce: fix labels

- tunnel-server/src/ssh/base-server.ts
> Close connection on error in tunnel-server

- packages/compose-tunnel-agent/src/api-server/containers/index.ts
- tunnel-server/src/proxy/index.ts
- tunnel-server: always allow OPTIONS
- cta api: add container start/stop/restart
> cta more container api

- tunnel-server/src/app.ts
- tunnel-server/src/auth.ts
- tunnel-server/src/proxy/index.ts
- tunnel-server/src/session.ts
> auth refactor

- packages/cli-common/src/lib/text.ts
- packages/cli/package.json
- packages/cli/src/commands/init.ts
- packages/cli/src/help.ts
> cli: add logo

- packages/cli-common/src/lib/text.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/profile/cp.ts
- packages/cli/src/commands/profile/create.ts
- packages/cli/src/commands/profile/import.ts
- packages/cli/src/commands/profile/ls.ts
- packages/cli/src/commands/profile/use.ts
- packages/cli/src/fs.ts
- packages/cli/src/profile-command.ts
- packages/core/src/profile/config.ts
- packages/core/src/profile/store.ts
fixes #231 
```
➜  preevy git:(cli-profile-cp) ~/preevy/packages/cli/bin/dev profile cp --help
Copy a profile
USAGE
$ preevy profile cp [-D] [-f <value>] [--system-compose-file <value>] [-p <value>] [--json]
[--profile <value>] [--target-location <value> | --target-storage local|s3|gs] [--target-name
<value>] [--use]
FLAGS
--profile=<value>          Source profile name, defaults to the current profile
--target-location=<value>  Target profile location URL
--target-name=<value>      Target profile name
--target-storage=<option>  Target profile storage type
<options: local|s3|gs>
--use                      Mark the new profile as the current profile
GLOBAL FLAGS
-D, --debug                       Enable debug logging
-f, --file=<value>...             [default: ] Compose configuration file …
```
> add profile cp command

- .github/workflows/combine-prs.yaml
- packages/cli-common/package.json
- packages/cli-common/src/lib/common-flags.ts
- packages/cli/package.json
- packages/cli/src/commands/profile/config/update.ts
- packages/cli/src/commands/purge.ts
- packages/cli/src/help.ts
- packages/driver-azure/package.json
- packages/driver-gce/package.json
- packages/driver-kube-pod/package.json
- packages/driver-lightsail/package.json
- packages/plugin-github-pr-link/package.json
- packages/plugin-github-pr-link/src/commands/github-pr/link.ts
- patches/@oclif+core+3.12.0.patch
- yarn.lock
multiple flags such as `-f` were not parsed correctly due to a bug or misfeature in oclif.
- update oclif to the latest version with the minimal required changes
- create a patch from https://github.com/oclif/core/pull/880 to fix oclif's behavior
> fix multiple flags bug

- packages/cli-common/src/commands/base-command.ts
- packages/cli/.eslintignore
- packages/cli/src/commands/down.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/purge.ts
- packages/cli/src/driver-command.ts
- packages/cli/src/hooks/init/load-plugins.ts
- packages/core/src/driver/driver.ts
- packages/core/src/driver/machine-operations.ts
- packages/driver-azure/src/driver/index.ts
- packages/driver-gce/src/driver/index.ts
- packages/driver-kube-pod/src/driver/client/common.ts
- packages/driver-kube-pod/src/driver/client/dynamic/index.ts
- packages/driver-kube-pod/src/driver/client/dynamic/wait.ts
- packages/driver-kube-pod/src/driver/client/index.ts
- packages/driver-kube-pod/src/driver/client/k8s-helpers.ts
- packages/driver-kube-pod/src/driver/client/metadata.test.ts
- packages/driver-kube-pod/src/driver/client/metadata.ts
- packages/driver-kube-pod/src/driver/common.ts
- packages/driver-kube-pod/src/driver/creation-driver.ts
- packages/driver-kube-pod/src/driver/driver.ts
- packages/driver-kube-pod/src/driver/index.ts
- packages/driver-kube-pod/src/driver/questions.ts
- packages/driver-kube-pod/static/default-template.yaml.njk
- packages/driver-lightsail/src/driver/index.ts
- site/docs/deploy-runtimes/kube-pod.md
new environments now use a StatefulSet definition which [dynamically provisions](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) a persistent volume. Cluster must have a default StorageClass defined.
> kube driver: move to StatefulSet

- build_utils/lint-staged.config.cjs
- packages/core/src/compose-tunnel-agent-client.ts
- packages/core/src/login.ts
- tunnel-server/index.ts
- tunnel-server/package.json
- tunnel-server/src/app.ts
- tunnel-server/src/auth.ts
- tunnel-server/src/proxy/index.ts
- tunnel server: make saas optional config
- add diagnostic messages when throwing errors
- fix lint-staged config
> tunnel server: optional saas config

- site/docs/docker-extension.md
Hyperlinks are not working due to capitalization.
> docs: fix broken links in Docker extension docs

- packages/cli-common/src/hooks/init/load-plugins.ts
- packages/cli-common/src/lib/common-flags/index.ts
- packages/cli-common/src/lib/plugins/model.ts
- packages/cli/src/commands/logs.ts
- packages/cli/src/commands/up.ts
- packages/core/src/commands/build.ts
- packages/core/src/commands/model.ts
- packages/core/src/commands/up.ts
- packages/core/src/compose/files.ts
- packages/core/src/compose/model.ts
- packages/core/src/compose/remote.ts
- packages/core/src/index.ts
- add flag to allow setting the project directory like in the `docker compose` CLI
- remove usages of cwd where applicable
fixes #382
> add `--project-directory` flag

- site/docs/docker-extension.md
Embed a video - Explaining Deploy to cloud feature
> docs: Update Docker Extension documentation

- tunnel-server/src/metrics.ts
- tunnel-server/src/ssh/index.ts
> Update ssh connection metric to use clientId for aggression

- site/docs/ci/index.mdx
> docs: small updates to CI documentation

- packages/driver-kube-pod/static/default-template.yaml.njk
fix errors while starting the Docker server on GKE nodes:
```
failed to start daemon: Error initializing network controller: error creating default bridge network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.10 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain POSTROUTING
(exit status 4))
```
> kube driver: change default dind image to alpine

- .gitignore
- .vscode/settings.json
- packages/cli-common/src/index.ts
- packages/cli-common/src/lib/common-flags/index.ts
- packages/cli-common/src/lib/common-flags/tunnel-server-flags.ts
- packages/cli/src/commands/env/metadata.ts
- packages/cli/src/commands/proxy/connect.ts
- packages/cli/src/commands/up.ts
- packages/cli/src/commands/urls.ts
- packages/cli/src/driver-command.ts
- packages/core/src/compose-tunnel-agent-client.ts
- packages/core/src/driver/machine-operations.ts
- packages/core/src/index.ts
- **local dev: fix gitignore and vscode settings**
- **add env metadata command**
> add env metadata command

- packages/driver-lightsail/src/driver/client.ts
- packages/driver-lightsail/src/driver/tags.ts
AWS warns about the End of Standard Support for `ubuntu_20_04` blueprint instances. This PR bumps the blueprint id to the current/recommended  value `ubuntu_24_04`.
> feat: Bump AWS Lightsail blueprint to ubuntu_24_04
